-- vim:fileencoding=utf-8:foldmethod=marker

local M = {}
local O = require("neopywal").options
local U = require("neopywal.util")

M.get = function(colors)
	local fill_bg = U.blend(colors.background, colors.foreground, 0.9)
	local unselected_bg = U.blend(colors.background, colors.foreground, 0.85)

	-- akinsho/bufferline.nvim
	return {
		--: Bufferline {{{
		BufferLineFill = { bg = fill_bg }, -- Filler color for line.

		-- BufferLinePick command.
		BufferLinePick = {
			bg = unselected_bg,
			fg = colors.color6,
			bold = true,
			italic = true,
		}, -- Pick selector for non-selected buffers.
		BufferLinePickVisible = { link = "BufferLinePick" }, -- Pick selector for selected buffer on non-current windows.
		BufferLinePickSelected = {
			bg = colors.background,
			fg = colors.color6,
			bold = true,
			italic = true,
		}, -- Pick selector for selected buffer.

		-- BufferLineGroupLabel = {  },
		-- BufferLineGroupSeparator = {  },
		BufferLineTruncMarker = { link = "BufferLineBuffer" },

		-- BufferLineIndicatorVisible = {  },
		-- BufferLineIndicatorSelected = {  },

		-- Close button.
		BufferLineCloseButton = { link = "BufferLineBuffer" }, -- Close button non-selected buffers.
		BufferLineCloseButtonVisible = { link = "BufferLineBufferVisible" }, -- Close button for selected buffer on non-current windows.
		BufferLineCloseButtonSelected = { fg = colors.color1 }, -- Close button for selected buffer.
		BufferLineTabClose = { bg = colors.color1, fg = colors.background }, -- Tab close button.

		-- Separators.
		BufferLineSeparator = {
			bg = O.transparent and colors.none or unselected_bg,
			fg = fill_bg,
		}, -- Separator for non-selected buffers.
		BufferLineSeparatorVisible = { link = "BufferLineSeparator" }, -- Separator for selected buffer on non-current windows.
		BufferLineSeparatorSelected = {
			bg = O.transparent and colors.none or colors.background,
			fg = fill_bg,
		}, -- Separator for selected buffer.
		BufferLineTabSeparator = { link = "BufferLineSeparator" }, -- Separator for non-selected tabs.
		BufferLineTabSeparatorSelected = { link = "BufferLineSeparatorSelected" }, -- Separator for selected tab.
		BufferLineOffsetSeparator = { link = "BufferLineFill" }, -- Offset separator for buffers.

		-- Numbers.
		BufferLineNumbers = { link = "BufferLineBuffer" }, -- Numbers for non-selected buffers.
		BufferLineNumbersVisible = { link = "BufferLineBufferVisible" }, -- Numbers for selected buffer on non-current windows.
		BufferLineNumbersSelected = { link = "BufferLineBufferSelected" }, -- Numbers for selected buffer.

		-- Tabs.
		BufferLineTab = {
			bg = O.transparent and colors.none or unselected_bg,
			fg = U.blend(colors.background, colors.foreground, 0.5),
		}, -- Text for non-selected tabs.
		BufferLineTabSelected = {
			bg = O.transparent and colors.none or colors.background,
			fg = colors.foreground,
			bold = true,
			italic = true,
		}, -- Text on selected tab.

		-- Buffers.
		BufferLineBuffer = { link = "BufferLineTab" }, -- Non-selected buffers.
		BufferLineBufferVisible = { link = "BufferLineTab" }, -- Non-current buffers windows.
		BufferLineBufferSelected = { link = "BufferLineTabSelected" }, -- Selected buffer.
		BufferLineBackground = { link = "BufferLineBufferVisible" }, -- Background & text for non-selected buffers.

		-- Modified icon.
		BufferLineModified = { link = "BufferLineBuffer" }, -- Icon color for non-selected modified buffers.
		BufferLineModifiedVisible = { link = "BufferLineBufferVisible" }, -- Icon color for selected modified buffer on non-current windows.
		BufferLineModifiedSelected = { bg = colors.background, fg = U.blend(colors.color1, colors.color3, 0.5) }, -- Icon color for selected modified buffer.

		-- String that's duplicated from two buffers.
		BufferLineDuplicate = { link = "BufferLineBuffer" }, -- String from a non-selected buffer that's duplicated.
		BufferLineDuplicateVisible = { link = "BufferLineBufferVisible" }, -- String from a non-current buffer that's duplicated.
		BufferLineDuplicateSelected = { link = "BufferLineBufferSelected" }, -- String of a selected buffer that's duplicated.

		-- Diagnostics.
		BufferLineDiagnostic = { link = "BufferLineBuffer" },
		BufferLineDiagnosticVisible = { link = "BufferLineBufferVisible" },
		BufferLineDiagnosticSelected = { link = "DiagnosticUnnecessary" },

		-- Buffer with errors.
		BufferLineError = { link = "BufferLineBuffer" }, -- Non-selected buffers with errors.
		BufferLineErrorVisible = { link = "BufferLineBufferVisible" }, -- Selected buffer with errors on non-current windows.
		BufferLineErrorSelected = { link = "DiagnosticError" }, -- Selected buffer with errors.
		BufferLineErrorDiagnostic = { link = "BufferLineError" },
		BufferLineErrorDiagnosticVisible = { link = "BufferLineErrorVisible" },
		BufferLineErrorDiagnosticSelected = { link = "BufferLineErrorSelected" },

		-- Buffer with warnings.
		BufferLineWarning = { link = "BufferLineBuffer" }, -- Non-selected buffers with warnings.
		BufferLineWarningVisible = { link = "BufferLineBufferVisible" }, -- Selected buffer with warnings on non-current windows.
		BufferLineWarningSelected = { link = "DiagnosticWarn" }, -- Selected buffer with warnings.
		BufferLineWarningDiagnostic = { link = "BufferLineWarning" },
		BufferLineWarningDiagnosticVisible = { link = "BufferLineWarningVisible" },
		BufferLineWarningDiagnosticSelected = { link = "BufferLineWarningSelected" },

		-- Buffer with hints.
		BufferLineHint = { link = "BufferLineBuffer" }, -- Non-selected buffers with hints.
		BufferLineHintVisible = { link = "BufferLineBufferVisible" }, -- Selected buffer with hints on non-current windows.
		BufferLineHintSelected = { link = "DiagnosticHint" }, -- Selected buffer with hints.
		BufferLineHintDiagnostic = { link = "BufferLineHint" },
		BufferLineHintDiagnosticVisible = { link = "BufferLineHintVisible" },
		BufferLineHintDiagnosticSelected = { link = "BufferLineHintSelected" },

		-- Buffer with informations.
		BufferLineInfo = { link = "BufferLineBuffer" }, -- Non-selected buffers with infos.
		BufferLineInfoVisible = { link = "BufferLineBufferVisible" }, -- Selected buffer with infos on non-current windows.
		BufferLineInfoSelected = { link = "DiagnosticInfo" }, -- Selected buffer with infos.
		BufferLineInfoDiagnostic = { link = "BufferLineInfo" },
		BufferLineInfoDiagnosticVisible = { link = "BufferLineInfoVisible" },
		BufferLineInfoDiagnosticSelected = { link = "BufferLineInfoSelected" },
		--: }}}
		--: BufferlineDevIconsDefault {{{
		--[[
			Used as the base highlight group for dev icons of non-selected buffers.
			Other bufferline default dev icon highlights link to this by default.
		--]]
		BufferLineDevIconDefault = { link = "BufferLineBuffer" },

		BufferLineDevIconAOSC = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconAac = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconAi = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconAlmalinu = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconAlpine = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconApp = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconApple = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconAppleScript = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconArch = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconArti = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconAvif = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconAwk = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconAzureCli = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBabelrc = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBackup = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBash = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBashProfile = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBashrc = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBat = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBazel = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBazelBuild = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBazelWorkspace = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBibTe = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBinaryGLTF = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBmp = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBrewfile = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBudgie = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconBzl = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconC = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCMake = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCMakeLists = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCPlusPlus = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCPlusPlusModule = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCSharpProject = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCentos = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCheckhealth = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCjs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconClojure = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconClojureC = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconClojureDart = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconClojureJS = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCobol = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCoffee = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconConf = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconConfigRu = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconConfiguration = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCp = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCpp = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCppm = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCrystal = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCsh = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCson = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCss = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCsv = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCts = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconCxxm = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconD = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconDart = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconDb = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconDebian = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconDeepin = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconDesktopEntry = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconDevuan = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconDiff = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconDoc = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconDockerfile = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconDrools = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconDropbo = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconDsStore = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconDump = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconE = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconEditorConfig = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconEdn = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconEe = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconEjs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconElementary = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconElf = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconElm = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconEmbeddedOpenTypeFont = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconEndeavour = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconEnv = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconEpp = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconErb = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconErl = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconEslintIgnore = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconEslintrc = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconExe = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconExs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconFavicon = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconFedora = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconFennel = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconFish = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconFlac = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconFortran = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconFreeBSD = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconFs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconFsharp = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconFsi = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconFsscript = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGDScript = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGemfile = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGemspec = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGentoo = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGif = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGitAttributes = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGitCommit = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGitConfig = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGitIgnore = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGitLogo = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGitModules = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGitlabCI = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGo = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGodotProject = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGraphQL = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGroovy = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGruntfile = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGui = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGulpfile = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconGvimrc = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconH = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconHaml = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconHaxe = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconHbs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconHee = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconHh = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconHpp = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconHrl = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconHs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconHtm = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconHtml = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconHuff = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconHurl = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconI = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconIco = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconIllumos = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconImportConfiguration = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconIni = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconJava = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconJavaScriptReactSpec = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconJavaScriptReactTest = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconJl = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconJpeg = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconJpegXl = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconJpg = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconJson = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconJson5 = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconJsonc = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconKali = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconKotlin = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconKotlinScript = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconKsh = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconLee = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconLess = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconLhs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconLicense = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconLinu = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconLiquid = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconLock = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconLog = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconLua = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconLuau = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconLuaurc = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconM4A = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconM4V = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMOV = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMageia = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMakefile = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconManjaro = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMarkdown = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMaterial = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMd = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMint = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMixLock = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMjs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMkv = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMl = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMli = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMotoko = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMp3 = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMp4 = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMpp = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMts = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconMustache = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconNPMIgnore = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconNPMrc = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconNi = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconNim = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconNixOS = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconNodeModules = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconNotebook = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconNswag = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconNushell = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconOPUS = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconOgg = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconOpenBSD = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconOpenSCAD = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconOpenTypeFont = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconOrgMode = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconOut = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPackageJson = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPackageLockJson = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPackedResource = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconParrot = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPdf = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPhp = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPl = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPm = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPng = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPop_OS = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPp = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPpt = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPrettierConfig = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPrisma = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconProcfile = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconProlog = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPsManifestfile = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPsScriptModulefile = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPsScriptfile = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPsb = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPsd = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPxd = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPxi = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPy = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPyc = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPyd = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPyi = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconPyo = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconQuery = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconR = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconRake = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconRakefile = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconRaspberryPiOS = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconRazorPage = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconRb = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconReScript = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconReScriptInterface = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconRedhat = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconRlib = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconRmd = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconRockyLinu = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconRproj = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconRs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconRss = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSabayon = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSass = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconScala = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconScheme = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconScss = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSettingsJson = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSh = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSig = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSlackware = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSlim = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSln = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSml = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSolidity = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSolus = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSpecJs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSpecTs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSql = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconStyl = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSuo = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSvelte = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSvelteConfig = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSvg = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSwift = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconSystemVerilog = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTFVars = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTSConfig = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTailwindConfig = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTcl = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTe = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTempl = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTerminal = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTerraform = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTestJs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTestTs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTextResource = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTextScene = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconToml = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTor = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTrueTypeFont = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTs = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTwig = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTxt = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTypeScriptReactSpec = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconTypeScriptReactTest = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconUbuntu = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconVHDL = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconVagrantfile = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconVala = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconVerilog = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconVim = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconVimrc = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconVlang = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconVoid = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconVue = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconWasm = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconWav = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconWebOpenFontFormat = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconWebm = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconWebmanifest = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconWebp = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconWebpack = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconWindows = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconXaml = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconXcPlayground = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconXls = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconXml = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconXul = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconYaml = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconYml = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconZig = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconZigObjectNotation = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconZorin = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconZsh = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconZshenv = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconZshprofile = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconZshrc = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconarduino = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconcuda = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconcudah = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconopenSUSE = { link = "BufferLineDevIconDefault" },
		BufferLineDevIconsbt = { link = "BufferLineDevIconDefault" },
		["BufferLineDevIconPy.typed"] = { link = "BufferLineDevIconDefault" },

		--: }}}
		--: BufferlineDevIconsInactive {{{
		--[[
			Used as the base highlight group for dev icons of selected buffers on non-current windows.
			Other bufferline inactive dev icon highlights link to this by default.
		--]]
		BufferLineDevIconDefaultInactive = { link = "BufferLineBuffer" },

		BufferLineDevIconAOSCInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconAacInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconAiInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconAlmalinuInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconAlpineInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconAppInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconAppleInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconAppleScriptInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconArchInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconArtiInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconAvifInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconAwkInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconAzureCliInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBabelrcInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBackupInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBashInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBashProfileInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBashrcInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBatInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBazelInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBazelBuildInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBazelWorkspaceInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBibTeInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBinaryGLTFInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBmpInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBrewfileInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBudgieInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconBzlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCMakeInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCMakeListsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCPlusPlusInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCPlusPlusModuleInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCSharpProjectInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCentosInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCheckhealthInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCjsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconClojureInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconClojureCInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconClojureDartInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconClojureJSInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCobolInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCoffeeInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconConfInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconConfigRuInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconConfigurationInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCpInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCppInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCppmInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCrystalInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCshInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCsonInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCssInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCsvInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCtsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconCxxmInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconDInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconDartInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconDbInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconDebianInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconDeepinInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconDesktopEntryInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconDevuanInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconDiffInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconDocInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconDockerfileInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconDroolsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconDropboInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconDsStoreInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconDumpInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconEInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconEditorConfigInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconEdnInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconEeInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconEjsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconElementaryInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconElfInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconElmInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconEmbeddedOpenTypeFontInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconEndeavourInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconEnvInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconEppInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconErbInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconErlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconEslintIgnoreInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconEslintrcInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconExeInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconExsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconFaviconInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconFedoraInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconFennelInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconFishInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconFlacInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconFortranInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconFreeBSDInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconFsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconFsharpInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconFsiInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconFsscriptInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGDScriptInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGemfileInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGemspecInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGentooInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGifInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGitAttributesInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGitCommitInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGitConfigInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGitIgnoreInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGitLogoInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGitModulesInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGitlabCIInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGoInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGodotProjectInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGraphQLInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGroovyInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGruntfileInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGuiInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGulpfileInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconGvimrcInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconHInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconHamlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconHaxeInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconHbsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconHeeInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconHhInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconHppInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconHrlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconHsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconHtmInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconHtmlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconHuffInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconHurlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconIInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconIcoInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconIllumosInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconImportConfigurationInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconIniInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconJavaInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconJavaScriptReactSpecInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconJavaScriptReactTestInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconJlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconJpegInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconJpegXlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconJpgInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconJsonInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconJson5Inactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconJsoncInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconKaliInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconKotlinInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconKotlinScriptInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconKshInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconLeeInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconLessInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconLhsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconLicenseInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconLinuInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconLiquidInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconLockInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconLogInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconLuaInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconLuauInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconLuaurcInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconM4AInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconM4VInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMOVInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMageiaInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMakefileInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconManjaroInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMarkdownInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMaterialInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMdInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMintInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMixLockInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMjsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMkvInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMliInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMotokoInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMp3Inactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMp4Inactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMppInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMtsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconMustacheInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconNPMIgnoreInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconNPMrcInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconNiInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconNimInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconNixOSInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconNodeModulesInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconNotebookInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconNswagInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconNushellInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconOPUSInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconOggInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconOpenBSDInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconOpenSCADInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconOpenTypeFontInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconOrgModeInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconOutInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPackageJsonInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPackageLockJsonInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPackedResourceInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconParrotInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPdfInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPhpInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPmInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPngInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPop_OSInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPpInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPptInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPrettierConfigInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPrismaInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconProcfileInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPrologInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPsManifestfileInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPsScriptModulefileInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPsScriptfileInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPsbInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPsdInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPxdInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPxiInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPyInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPycInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPydInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPyiInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconPyoInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconQueryInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconRInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconRakeInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconRakefileInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconRaspberryPiOSInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconRazorPageInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconRbInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconReScriptInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconReScriptInterfaceInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconRedhatInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconRlibInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconRmdInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconRockyLinuInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconRprojInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconRsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconRssInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSabayonInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSassInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconScalaInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSchemeInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconScssInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSettingsJsonInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconShInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSigInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSlackwareInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSlimInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSlnInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSmlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSolidityInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSolusInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSpecJsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSpecTsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSqlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconStylInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSuoInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSvelteInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSvelteConfigInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSvgInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSwiftInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconSystemVerilogInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTFVarsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTSConfigInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTailwindConfigInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTclInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTeInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTemplInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTerminalInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTerraformInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTestJsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTestTsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTextResourceInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTextSceneInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTomlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTorInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTrueTypeFontInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTwigInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTxtInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTypeScriptReactSpecInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconTypeScriptReactTestInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconUbuntuInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconVHDLInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconVagrantfileInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconValaInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconVerilogInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconVimInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconVimrcInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconVlangInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconVoidInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconVueInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconWasmInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconWavInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconWebOpenFontFormatInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconWebmInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconWebmanifestInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconWebpInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconWebpackInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconWindowsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconXamlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconXcPlaygroundInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconXlsInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconXmlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconXulInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconYamlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconYmlInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconZigInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconZigObjectNotationInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconZorinInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconZshInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconZshenvInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconZshprofileInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconZshrcInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconarduinoInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconcudaInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconcudahInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconopenSUSEInactive = { link = "BufferLineDevIconDefaultInactive" },
		BufferLineDevIconsbtInactive = { link = "BufferLineDevIconDefaultInactive" },
		["BufferLineDevIconPyInactive.typed"] = { link = "BufferLineDevIconDefaultInactive" },
		--: }}}
	}
end

return M
