-- vim:fileencoding=utf-8:foldmethod=marker:foldenable

local M = {}
local U = require("neopywal.util")
local O = require("neopywal").options

local function apply_plugin(option, highlights)
	local keys = {}
	for key in option:gmatch("[^.]+") do
		table.insert(keys, key)
	end

	local value = O.plugins
	for _, key in ipairs(keys) do
		if type(value) == "table" and value[key] ~= nil then
			value = value[key]
		else
			return {}
		end
	end

	if type(value) ~= "boolean" then
		return {}
	end

	return value and highlights or {}
end

M.get = function(colors)
	return vim.tbl_deep_extend(
		"force",
		{},
		--: neoclide/coc.nvim {{{
		apply_plugin("coc", {
			CocHighlightText = { bold = true },
			CocHoverRange = { bold = true, underline = true },
			CocHintHighlight = { fg = colors.color2, undercurl = true },
			CocErrorFloat = { bg = colors.color8, fg = colors.color1 },
			CocWarningFloat = { bg = colors.color8, fg = colors.color3 },
			CocInfoFloat = { bg = colors.color8, fg = colors.color4 },
			CocHintFloat = { bg = colors.color8, fg = colors.color2 },
			CocCodeLens = { fg = colors.color8 },
			CocErrorSign = { fg = colors.color1 },
			CocWarningSign = { fg = colors.color3 },
			CocInfoSign = { fg = colors.color4 },
			CocHintSign = { link = "Label" },
			CocErrorHighlight = { fg = colors.color1, undercurl = true },
			CocWarningHighlight = { fg = colors.color3, undercurl = true },
			CocInfoHighlight = { fg = colors.color4, undercurl = true },
			CocWarningVirtualText = { fg = colors.color8 },
			CocErrorVirtualText = { fg = colors.color8 },
			CocInfoVirtualText = { fg = colors.color8 },
			CocHintVirtualText = { fg = colors.color8 },
			CocGitAddedSign = { fg = colors.color2 },
			CocGitChangeRemovedSign = { fg = colors.color5 },
			CocGitChangedSign = { fg = colors.color4 },
			CocGitRemovedSign = { fg = colors.color1 },
			CocGitTopRemovedSign = { fg = colors.color1 },
			CocExplorerBufferRoot = { fg = colors.color1 },
			CocExplorerBufferExpandIcon = { fg = colors.color4 },
			CocExplorerBufferBufnr = { fg = colors.color3 },
			CocExplorerBufferModified = { fg = colors.color1 },
			CocExplorerBufferBufname = { fg = colors.color8 },
			CocExplorerBufferFullpath = { fg = colors.color8 },
			CocExplorerFileRoot = { fg = colors.color1 },
			CocExplorerFileExpandIcon = { fg = colors.color4 },
			CocExplorerFileFullpath = { fg = colors.color8 },
			CocExplorerFileDirectory = { fg = colors.color2 },
			CocExplorerFileGitStage = { fg = colors.color4 },
			CocExplorerFileGitUnstage = { fg = colors.color3 },
			CocExplorerFileSize = { fg = colors.color4 },
			CocExplorerTimeAccessed = { fg = colors.color5 },
			CocExplorerTimeCreated = { fg = colors.color5 },
			CocExplorerTimeModified = { fg = colors.color5 },
			CocExplorerFileRootName = { fg = colors.color11 },
			CocExplorerBufferNameVisible = { fg = colors.color2 },
		}),
		--: }}}
		--: dense-analysis/ale {{{
		apply_plugin("ale", {
			ALEError = { fg = colors.color1, undercurl = true },
			ALEWarning = { fg = colors.color3, undercurl = true },
			ALEInfo = { fg = colors.color4, undercurl = true },
			ALEErrorSign = { fg = colors.color1 },
			ALEWarningSign = { fg = colors.color3 },
			ALEInfoSign = { fg = colors.color4 },
			ALEVirtualTextError = { link = "DiagnosticError" },
			ALEVirtualTextWarning = { link = "DiagnosticWarn" },
			ALEVirtualTextInfo = { link = "DiagnosticInfo" },
			ALEVirtualTextStyleError = { link = "ALEVirtualTextError" },
			ALEVirtualTextStyleWarning = { link = "ALEVirtualTextWarning" },
		}),
		--: }}}
		--: airblade/vim-gitgutter {{{
		apply_plugin("git_gutter", {
			GitGutterAdd = { fg = colors.color2 },
			GitGutterChange = { fg = colors.color4 },
			GitGutterDelete = { fg = colors.color1 },
			GitGutterChangeDelete = { fg = colors.color5 },
		}),
		--: }}}
		--: hrsh7th/nvim-cmp {{{
		apply_plugin("nvim_cmp", {
			CmpDocumentation = { link = "FloatBorder" },
			CmpDocumentationBorder = { link = "FloatBorder" },
			CmpItemAbbr = { bg = colors.none, fg = colors.foreground },
			CmpItemAbbrDeprecated = { bg = colors.none, fg = colors.color2, strikethrough = true },
			CmpItemAbbrMatch = { bg = colors.none, fg = colors.color4 },
			CmpItemAbbrMatchFuzzy = { bg = colors.none, fg = colors.color5 },
			CmpItemKind = { bg = colors.none, fg = colors.foreground },
			CmpItemMenu = { bg = colors.none, fg = colors.color2 },
			CmpItemKindDefault = { bg = colors.none, fg = colors.foreground },
			CmpItemAbbrDefault = { bg = colors.none, fg = colors.foreground },
			CmpItemAbbrDeprecatedDefault = { bg = colors.none, fg = colors.color8, strikethrough = true },
			CmpItemAbbrMatchDefault = { bg = colors.none, fg = colors.foreground },
			CmpItemAbbrMatchFuzzyDefault = { bg = colors.none, fg = colors.foreground },
			CmpItemMenuDefault = { bg = colors.none, fg = colors.foreground },

			-- Kind support:
			CmpItemKindKeyword = { bg = colors.none, fg = colors.color1 }, -- Link Keyword
			CmpItemKindOperator = { bg = colors.none, fg = colors.color1 }, -- Link Operator
			CmpItemKindEnum = { link = "CmpItemKindKeyword" },
			CmpItemKindFunction = { bg = colors.none, fg = colors.color2 }, -- Link Function
			CmpItemKindField = { bg = colors.none, fg = colors.color2 }, -- Link @variable.member
			CmpItemKindProperty = { bg = colors.none, fg = colors.color2 }, -- Link @property
			CmpItemKindMethod = { link = "CmpItemKindFunction" },
			CmpItemKindColor = { bg = colors.none, fg = colors.color3 },
			CmpItemKindInterface = { bg = colors.none, fg = colors.color4 },
			CmpItemKindFolder = { bg = colors.none, fg = colors.color4 }, -- Link Directory
			CmpItemKindVariable = { bg = colors.none, fg = colors.color4 }, -- Link Variable
			CmpItemKindEvent = { link = "CmpItemKindVariable" },
			CmpItemKindConstructor = { bg = colors.none, fg = colors.color5 }, -- Link Special
			CmpItemKindModule = { bg = colors.none, fg = colors.color5 }, -- Link Include
			CmpItemKindUnit = { bg = colors.none, fg = colors.color5 }, -- Link Number
			CmpItemKindSnippet = { link = "CmpItemKindModule" },
			CmpItemKindClass = { bg = colors.none, fg = colors.color6 }, -- Link StorageClass
			CmpItemKindStruct = { bg = colors.none, fg = colors.color6 }, -- Link Structure
			CmpItemKindCopilot = { bg = colors.none, fg = colors.color6 },
			CmpItemKindTabNine = { bg = colors.none, fg = colors.color6 },
			CmpItemKindTypeParameter = { bg = colors.none, fg = colors.color11 }, -- Link Identifier
			CmpItemKindConstant = { bg = colors.none, fg = colors.color11 }, -- Link Constant
			CmpItemKindValue = { link = "CmpItemKindConstant" },
			CmpItemKindEnumMember = { link = "CmpItemKindConstant" },
			CmpItemKindText = { bg = colors.none, fg = U.lighten(colors.background, 30) },
			CmpItemKindFile = { link = "CmpItemKindText" },
			CmpItemKindReference = { link = "CmpItemKindText" },
		}),
		--: }}}
		--: neovim/nvim-lspconfig {{{
		apply_plugin("lspconfig", {
			-- These groups are for the native LSP client. Some other LSP clients may
			-- use these groups, or use their own. Consult your LSP client's documentation.

			LspReferenceText = { bold = true }, -- used for highlighting "text" references
			LspReferenceRead = { bold = true }, -- used for highlighting "read" references
			LspReferenceWrite = { bold = true }, -- used for highlighting "write" references
			LspInlayHint = { link = "NonText" },
			LspInfoTitle = { link = "Title" },
			LspInfoTip = { link = "Comment" },
			LspInfoList = { link = "Function" },
			LspInfoBorder = { link = "Label" },
			LspInfoFiletype = { link = "Type" },
			LspCodeLens = { link = "Comment" },
			LspSignatureActiveParameter = { link = "Visual" },

			LspDiagnosticsHint = { link = "DiagnosticHint" },
			LspDiagnosticsInformation = { link = "DiagnosticInfo" },
			LspDiagnosticsWarning = { link = "DiagnosticWarn" },
			LspDiagnosticsError = { link = "DiagnosticError" },

			DiagnosticVirtualTextError = { bg = U.alpha(colors.color1, 0.2), fg = colors.color1 }, -- Used for "Error" diagnostic virtual text
			DiagnosticVirtualTextWarn = { bg = U.alpha(colors.color11, 0.2), fg = colors.color11 }, -- Used for "Warning" diagnostic virtual text
			DiagnosticVirtualTextInfo = { bg = U.alpha(colors.foreground, 0.2), fg = colors.foreground }, -- Used for "Information" diagnostic virtual text
			DiagnosticVirtualTextHint = { bg = U.alpha(colors.color6, 0.2), fg = colors.color6 }, -- Used for "Hint" diagnostic virtual text

			DiagnosticUnderlineError = { sp = colors.color1, undercurl = true }, -- Used to underline "Error" diagnostics
			DiagnosticUnderlineWarn = { sp = colors.color11, undercurl = true }, -- Used to underline "Warning" diagnostics
			DiagnosticUnderlineInfo = { sp = colors.foreground, undercurl = true }, -- Used to underline "Information" diagnostics
			DiagnosticUnderlineHint = { sp = colors.color6, undercurl = true }, -- Used to underline "Hint" diagnostics
		}),
		--: }}}
		--: Lazy.nvim {{{
		apply_plugin("lazy", {
			LazyProgressTodo = { link = "LineNr" },
			LazyProgressDone = { link = "Constant" },
			LazySpecial = { link = "SpecialChar" },
			LazyDir = { fg = colors.color11 },
			LazyNoCond = { link = "DiagnosticWarn" },
			LazyNormal = { link = "NormalFloat" },
			LazyValue = { link = "String" },
			LazyUrl = { fg = colors.color11 },
			LazyLocal = { link = "Constant" },
			LazyProp = { link = "Conceal" },
			LazyDimmed = { link = "Conceal" },
			LazyCommitType = { link = "Title" },
			LazyCommitIssue = { link = "Number" },
			LazyCommitScope = { italic = true },
			LazyCommit = { fg = colors.color1 },
			LazyH1 = { bg = colors.color4, fg = colors.background, bold = true, italic = true },
			LazyH2 = { bold = true },
			LazyReasonRuntime = { link = "Macro" },
			LazyComment = { link = "Comment" },
			LazyReasonRequire = { fg = colors.color3 },
			LazyReasonImport = { link = "Identifier" },
			LazyReasonCmd = { link = "Operator" },
			LazyReasonFt = { link = "Character" },
			LazyButton = { bg = colors.color8, bold = true },
			LazyReasonSource = { link = "Character" },
			LazyButtonActive = { link = "LazyH1" },
			LazyReasonStart = { fg = colors.color2 },
			LazyTaskOutput = { link = "MsgArea" },
			LazyReasonKeys = { link = "Statement" },
			LazyReasonEvent = { link = "Constant" },
			LazyReasonPlugin = { link = "Special" },
			LazyTaskError = { link = "ErrorMsg" },
			LazyBackdrop = { bg = "#000000" },
		}),
		--: }}}
		--: nvim-neo-tree/neo-tree.nvim {{{
		apply_plugin("neotree", {
			NeoTreeDirectoryName = { link = "Directory" },
			NeoTreeDirectoryIcon = { link = "Directory" },
			NeoTreeNormal = { link = "Normal" },
			NeoTreeNormalNC = { link = "NormalNC" },
			NeoTreeExpander = { link = "Comment" },
			NeoTreeIndentMarker = { link = "NeoTreeExpander" },
			NeoTreeRootName = { link = "Directory" },
			NeoTreeSymbolicLinkTarget = { fg = colors.color6 },
			NeoTreeModified = { fg = colors.color11 },

			NeoTreeGitIgnored = { link = "Comment" },
			NeoTreeGitModified = { link = "NeoTreeModified" },
			NeoTreeGitAdded = { fg = colors.color2 },
			NeoTreeGitConflict = { fg = colors.color1 },
			NeoTreeGitDeleted = { fg = colors.color1 },
			NeoTreeGitUnstaged = { fg = colors.color1 },
			NeoTreeGitUntracked = { fg = colors.color5 },
			NeoTreeGitStaged = { fg = colors.color2 },

			NeoTreeFloatBorder = { link = "FloatBorder" },
			NeoTreeFloatTitle = { link = "FloatTitle" },
			NeoTreeTitleBar = { bg = colors.color4, fg = colors.background },
			NeoTreeFileNameOpened = { fg = colors.color5 },
			NeoTreeDimText = { link = "Comment" },
			NeoTreeFilterTerm = { fg = colors.color2, bold = true },
			NeoTreeTabActive = { fg = colors.color13, bold = true },
			NeoTreeTabInactive = { bg = colors.color8, fg = colors.color7 },
			NeoTreeTabSeparatorActive = { fg = colors.background },
			NeoTreeTabSeparatorInactive = { bg = colors.color8, fg = colors.color8 },
			NeoTreeVertSplit = { bg = colors.color8, fg = colors.background },
			NeoTreeStatusLineNC = { fg = colors.background },
			NeoTreeDotfile = { link = "Normal" },
			NeoTreeHiddenByName = { link = "NeoTreeDotfile" },
			NeoTreeWindowsHidden = { link = "NeoTreeDotfile" },
			NeoTreeCursorLine = { link = "CursorLine" },
			NeoTreeFileIcon = { link = "NeoTreeDirectoryIcon" },
			NeoTreePreview = { link = "Search" },
			NeoTreeGitRenamed = { link = "NeoTreeGitModified" },
			NeoTreeFileStats = { link = "Comment" },
			NeoTreeFileStatsHeader = { link = "Comment", bold = true },
			NeoTreeSignColumn = { link = "SignColumn" },
			NeoTreeStatusLine = { link = "StatusLine" },
			NeoTreeWinSeparator = { link = "WinSeparator" },
			NeoTreeEndOfBuffer = { link = "EndOfBuffer" },
			NeoTreeFloatNormal = { link = "NormalFloat" },
			NeoTreeBufferNumber = { link = "SpecialChar" },
			NeoTreeMessage = { link = "Comment", italic = true },
			NeoTreeFadeText1 = { link = "Comment" },
			NeoTreeFadeText2 = { link = "Comment" },
		}),
		--: }}}
		--: akinsho/bufferline.nvim {{{
		apply_plugin("bufferline", {
			BufferLineBackground = { link = "TabLine" },
			BufferLineFill = { link = "TabLineFill" },
			BufferLineGroupLabel = { fg = colors.color7 },
			BufferLineGroupSeparator = { fg = colors.color7 },
			BufferLineTruncMarker = { fg = colors.color7 },
			BufferLineBuffer = { bg = colors.color1, fg = colors.color2 },
			BufferLineBufferVisible = { fg = colors.color7 },
			BufferLineBufferSelected = { link = "BufferLineTabSelected" },
			BufferLineDuplicate = { fg = colors.color7 },
			BufferLineDuplicateVisible = { fg = colors.color7 },
			BufferLineDuplicateSelected = { fg = colors.color3, bold = true, italic = true },
			BufferLineTab = { fg = colors.color7 },
			BufferLineTabSelected = { link = "TabLineSel" },
			BufferLineTabSeparator = { fg = colors.background },
			BufferLineTabSeparatorSelected = { fg = colors.color4, bold = true },
			BufferLineTabClose = { bg = colors.color1, fg = colors.background, bold = true },
			BufferLineIndicatorVisible = { fg = colors.color7 },
			BufferLineIndicatorSelected = { link = "BufferLineTabSelected" },
			BufferLineSeparator = { fg = colors.background },
			BufferLineSeparatorVisible = { fg = colors.background },
			BufferLineSeparatorSelected = { fg = colors.background },
			BufferLineOffsetSeparator = { fg = colors.background },
			BufferLineCloseButton = { fg = colors.color1, bold = true },
			BufferLineCloseButtonVisible = { fg = colors.color1 },
			BufferLineCloseButtonSelected = { fg = colors.color1, bold = true, italic = true },
			BufferLineNumbers = { fg = colors.color7 },
			BufferLineNumbersVisible = { fg = colors.color7 },
			BufferLineNumbersSelected = { fg = colors.color7, bold = true, italic = true },
			BufferLineError = { fg = colors.color1 },
			BufferLineErrorVisible = { fg = colors.color1 },
			BufferLineErrorSelected = { fg = colors.color1, bold = true, italic = true },
			BufferLineErrorDiagnostic = { fg = colors.color1 },
			BufferLineErrorDiagnosticVisible = { fg = colors.color1 },
			BufferLineErrorDiagnosticSelected = { fg = colors.color1, bold = true, italic = true },
			BufferLineWarning = { fg = colors.color3 },
			BufferLineWarningVisible = { fg = colors.color3 },
			BufferLineWarningSelected = { fg = colors.color3, bold = true, italic = true },
			BufferLineWarningDiagnostic = { fg = colors.color3 },
			BufferLineWarningDiagnosticVisible = { fg = colors.color3 },
			BufferLineWarningDiagnosticSelected = { fg = colors.color3, bold = true, italic = true },
			BufferLineInfo = { fg = colors.color6 },
			BufferLineInfoVisible = { fg = colors.color6 },
			BufferLineInfoSelected = { fg = colors.color6, bold = true, italic = true },
			BufferLineInfoDiagnostic = { fg = colors.color6 },
			BufferLineInfoDiagnosticVisible = { fg = colors.color6 },
			BufferLineInfoDiagnosticSelected = { fg = colors.color6, bold = true, italic = true },
			BufferLineHint = { fg = colors.color5 },
			BufferLineHintVisible = { fg = colors.color5 },
			BufferLineHintSelected = { fg = colors.color5, bold = true, italic = true },
			BufferLineHintDiagnostic = { fg = colors.color5 },
			BufferLineHintDiagnosticVisible = { fg = colors.color5 },
			BufferLineHintDiagnosticSelected = { fg = colors.color5, bold = true, italic = true },
			BufferLineDiagnostic = { fg = colors.color2 },
			BufferLineDiagnosticVisible = { fg = colors.color2 },
			BufferLineDiagnosticSelected = { fg = colors.color2, bold = true, italic = true },
			BufferLineModified = { fg = colors.color11 },
			BufferLineModifiedVisible = { fg = colors.color11 },
			BufferLineModifiedSelected = { fg = colors.color11, bold = true, italic = true },
			BufferLinePick = { fg = colors.color7 },
			BufferLinePickVisible = { fg = colors.color7 },
			BufferLinePickSelected = { fg = colors.color7, bold = true, italic = true },
			--: BufferlineDevIcons {{{
			-- BufferLineDevIconPy.typed            = { bg = colors.background, fg = colors.color7 },
			BufferLineDevIconDefaultSelected = { bg = colors.background, fg = colors.color7, bold = true },
			BufferLineDevIconDefault = { bg = colors.background, fg = colors.color7 },
			BufferLineDevIconBazelWorkspace = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconLess = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconClojure = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconHpp = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCSharpProject = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconNodeModules = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconKotlinScript = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconEdn = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCjs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconJpegXl = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconXul = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconH = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconVala = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconVHDL = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCp = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPp = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSabayon = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTerraform = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconC = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconScheme = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconBashrc = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSystemVerilog = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconRedhat = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconHrl = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconVlang = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconConfiguration = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconRaspberryPiOS = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconYml = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconBashProfile = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconParrot = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconVimrc = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTrueTypeFont = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconopenSUSE = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTwig = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconcuda = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPy = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconLicense = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconRake = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconWebmanifest = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconLog = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTFVars = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconR = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMageia = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconAi = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconNushell = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCts = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSettingsJson = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconErb = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTestTs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconFennel = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGDScript = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGraphQL = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTestJs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconLuaurc = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconExe = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconJl = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGitlabCI = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMts = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPrisma = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconReScriptInterface = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTcl = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconElf = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTextScene = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconFedora = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconBabelrc = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconEslintrc = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconEditorConfig = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCsh = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconElementary = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconDsStore = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconErl = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconDevuan = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconKsh = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTypeScriptReactSpec = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconArch = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconDeepin = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconJavaScriptReactSpec = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconDb = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconDebian = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCobol = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconRss = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconConf = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCxxm = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSass = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconOrgMode = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSig = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSql = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCpp = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconRazorPage = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPyi = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconXaml = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTerminal = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCppm = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconConfigRu = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconYaml = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconXml = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconNim = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconScss = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCPlusPlusModule = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGitModules = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconScala = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGemspec = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconZshenv = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconBazel = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPxd = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconAzureCli = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconAppleScript = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconApp = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconDockerfile = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconRakefile = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconZigObjectNotation = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSvelte = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconEnv = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconImportConfiguration = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconRs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTailwindConfig = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconOut = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconBazelBuild = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSvelteConfig = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconNPMIgnore = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconReScript = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPackageLockJson = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconQuery = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconNswag = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGvimrc = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMixLock = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCPlusPlus = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMarkdown = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconarduino = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconZig = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconFavicon = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPm = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGitConfig = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconJson5 = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTxt = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconE = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPl = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconJava = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconLiquid = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconZshprofile = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconIni = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconHh = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconBrewfile = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconVerilog = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconEslintIgnore = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconZshrc = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMakefile = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPackageJson = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconStyl = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconBzl = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCMake = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconZorin = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconLua = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconNixOS = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconRockyLinu = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconHaml = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGui = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconClojureJS = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTextResource = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconHtml = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconLhs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconEndeavour = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSlackware = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTempl = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGentoo = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconOpenBSD = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconWebpack = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconIllumos = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconKali = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSolus = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSpecTs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconVim = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSuo = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconClojureDart = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconRb = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSml = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconBudgie = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMli = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconHbs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPxi = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconArti = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconEe = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMjs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconExs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconNi = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPsScriptfile = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconAOSC = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPng = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconBackup = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconAlpine = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCrystal = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPsScriptModulefile = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconAlmalinu = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconElm = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCentos = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconManjaro = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconUbuntu = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconApple = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconLuau = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconFreeBSD = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGitIgnore = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconHurl = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconDart = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconsbt = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSpecJs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconHs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGo = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCsv = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCss = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconKotlin = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconProlog = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTe = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconDesktopEntry = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconJpg = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTypeScriptReactTest = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMd = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconJsonc = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconM4A = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconVoid = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconVue = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconWebOpenFontFormat = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPop_OS = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCoffee = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconHtm = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSwift = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSln = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconHee = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGif = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMpp = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconZsh = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconJavaScriptReactTest = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPackedResource = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconDump = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconI = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCMakeLists = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconBibTe = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPhp = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconNotebook = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTSConfig = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSh = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconD = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGroovy = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconNPMrc = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconLinu = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconAwk = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPyd = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPyc = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPsd = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPsb = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconProcfile = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPpt = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPrettierConfig = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconOpenTypeFont = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconOPUS = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconOgg = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMp4 = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMp3 = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMOV = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMotoko = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMkv = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMint = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconM4V = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSvg = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMaterial = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconLock = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconRmd = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconJpeg = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconClojureC = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconIco = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconHuff = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconHaxe = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGulpfile = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGruntfile = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGodotProject = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconBinaryGLTF = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCheckhealth = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconFlac = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconDropbo = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconToml = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconDrools = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconDoc = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconBmp = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconLee = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMl = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGemfile = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconDiff = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconAvif = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconVagrantfile = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconBash = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconFsscript = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGitLogo = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconWindows = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconEpp = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPsManifestfile = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconEjs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGitCommit = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconCson = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconAac = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPyo = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconRlib = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconRproj = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconEmbeddedOpenTypeFont = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSlim = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconJson = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconFish = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconMustache = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconWav = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconWebm = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconWebp = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconcudah = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconXcPlayground = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconXls = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconFortran = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconGitAttributes = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconSolidity = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconOpenSCAD = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconPdf = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconFsi = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconTor = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconFsharp = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconFs = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconWasm = { link = "BufferLineDevIconDefault" },
			BufferLineDevIconBat = { link = "BufferLineDevIconDefault" },
			--: }}}
		}),
		--: }}}
		--: folke/which-key.nvim {{{
		apply_plugin("which_key", {
			WhichKey = { fg = colors.color1 },
			WhichKeyGroup = { fg = colors.color6 },
			WhichKeyDesc = { fg = colors.foreground },
			WhichKeySeperator = { fg = colors.color11 },
			WhichKeyValue = { link = "Comment" },
			WhichKeySeparator = { link = "Comment" },
			WhichKeyBorder = { link = "FloatBorder" },
			WhichKeyFloat = { link = "NormalFloat" },
		}),
		--: }}}
		--: nvimdev/dashboard-nvim {{{
		apply_plugin("dashboard", {
			DashboardShortCut = { fg = colors.color6 },
			DashboardHeader = { fg = colors.color4 },
			DashboardCenter = { fg = colors.color5 },
			DashboardFooter = { fg = colors.color4 },
			DashboardKey = { fg = colors.color11 },
			DashboardDesc = { fg = colors.color6 },
			DashboardIcon = { fg = colors.color6, bold = true },
		}),
		--: }}}
		--: goolord/alpha-nvim {{{
		apply_plugin("alpha", {
			AlphaShortcut = { fg = colors.color11 },
			AlphaHeader = { fg = colors.color4 },
			AlphaHeaderLabel = { fg = colors.color11 },
			AlphaFooter = { fg = colors.color4 },
			AlphaButtons = { fg = colors.color6 },
		}),
		--: }}}
		--: lukas-reineke/indent-blankline.nvim {{{
		apply_plugin("indent_blankline", {
			IndentBlanklineChar = { link = "Comment" },
		}),
		--: }}}
		--: vim.org/netrw {{{
		--: https://www.vim.org/scripts/script.php?script_id=1075
		apply_plugin("netrw", {
			netrwDir = { link = "Directory" },
			netrwClassify = { fg = colors.color2 },
			netrwLink = { fg = colors.color8 },
			netrwSymLink = { fg = colors.foreground },
			netrwExe = { fg = colors.color1 },
			netrwComment = { link = "Comment" },
			netrwList = { fg = colors.color3 },
			netrwHelpCmd = { fg = colors.color4 },
			netrwCmdSep = { fg = colors.color8 },
			netrwVersion = { fg = colors.color5 },
		}),
		--: }}}
		--: mbbill/undotree {{{
		apply_plugin("undotree", {
			UndotreeSavedBig = { fg = colors.color1, bold = true },
			UndotreeNode = { fg = colors.color4 },
			UndotreeNodeCurrent = { fg = colors.color5 },
			UndotreeSeq = { fg = colors.color2 },
			UndotreeCurrent = { fg = colors.color4 },
			UndotreeNext = { fg = colors.color3 },
			UndotreeTimeStamp = { fg = colors.color8 },
			UndotreeHead = { fg = colors.color5 },
			UndotreeBranch = { fg = colors.color4 },
			UndotreeSavedSmall = { fg = colors.color1 },
		}),
		--: }}}
		--: nvim-telescope/telescope.nvim {{{
		apply_plugin("telescope", {
			TelescopeNormal = { link = "Normal" },
			TelescopeBorder = { link = "FloatBorder" },
			TelescopeSelection = { link = "CursorLine" },
			TelescopeMatching = { fg = colors.color4, bold = true },
			TelescopePromptBorder = { link = "TelescopeBorder" },
			TelescopePromptNormal = { fg = colors.foreground },
			TelescopePromptPrefix = { fg = colors.color4, bold = true },
			TelescopePreviewTitle = { fg = colors.color3 },
			TelescopePromptTitle = { fg = colors.color4 },
			TelescopeResultsTitle = { fg = colors.color6 },
			TelescopeSelectionCaret = { fg = colors.color6 },
			TelescopeResultsVariable = { link = "SpecialChar" },
			TelescopeResultsStruct = { link = "Struct" },
			TelescopeResultsOperator = { link = "Operator" },
			TelescopeResultsMethod = { link = "Method" },
			TelescopeResultsFunction = { link = "Function" },
			TelescopeResultsField = { link = "Function" },
			TelescopeResultsConstant = { link = "Constant" },
			TelescopeResultsClass = { link = "Function" },
			TelescopePreviewMessageFillchar = { link = "TelescopePreviewMessage" },
			TelescopePreviewMessage = { link = "TelescopePreviewNormal" },
			TelescopePreviewNormal = { link = "TelescopeNormal" },
			TelescopePreviewDate = { link = "Directory" },
			TelescopePreviewGroup = { link = "Constant" },
			TelescopePreviewUser = { link = "Constant" },
			TelescopePreviewSize = { link = "String" },
			TelescopePreviewSticky = { link = "Keyword" },
			TelescopePreviewHyphen = { link = "NonText" },
			TelescopePreviewExecute = { link = "String" },
			TelescopePreviewWrite = { link = "Statement" },
			TelescopePreviewRead = { link = "Constant" },
			TelescopePreviewSocket = { link = "Statement" },
			TelescopePreviewLink = { link = "Special" },
			TelescopePreviewBlock = { link = "Constant" },
			TelescopePreviewDirectory = { link = "Directory" },
			TelescopePreviewCharDev = { link = "Constant" },
			TelescopePreviewPipe = { link = "Constant" },
			TelescopePreviewMatch = { link = "Search" },
			TelescopePreviewLine = { link = "Visual" },
			TelescopePromptCounter = { link = "NonText" },
			TelescopeTitle = { link = "TelescopeBorder" },
			TelescopePreviewBorder = { link = "TelescopeBorder" },
			TelescopeResultsBorder = { link = "TelescopeBorder" },
			TelescopeResultsNormal = { link = "TelescopeNormal" },
			TelescopeMultiIcon = { link = "Identifier" },
			TelescopeMultiSelection = { link = "Type" },
			TelescopeResultsDiffUntracked = { link = "NonText" },
			TelescopeResultsDiffDelete = { link = "DiffDelete" },
			TelescopeResultsDiffAdd = { link = "DiffAdd" },
			TelescopeResultsDiffChange = { link = "DiffChange" },
			TelescopeResultsSpecialComment = { link = "SpecialComment" },
			TelescopeResultsComment = { link = "Comment" },
			TelescopeResultsNumber = { link = "Number" },
			TelescopeResultsIdentifier = { link = "Identifier" },
			TelescopeResultsLineNr = { link = "LineNr" },
		}),
		--: }}}
		--: mini.nvim {{{
		--: mini.indentscope {{{
		apply_plugin("mini.indentscope", {
			MiniIndentscopeSymbol = { link = "Comment" },
			MiniIndentscopeSymbolOff = { link = "MiniIndentscopeSymbol" },
		}),
		--: }}}
		--: mini.statusline {{{
		apply_plugin("mini.statusline", {
			MiniStatuslineModeNormal = { bg = colors.color4, fg = colors.background, bold = true },
			MiniStatuslineModeVisual = { bg = colors.color5, fg = colors.background, bold = true },
			MiniStatuslineModeInsert = { bg = colors.color6, fg = colors.background, bold = true },
			MiniStatuslineModeCommand = { bg = colors.color1, fg = colors.background, bold = true },
			MiniStatuslineModeReplace = { bg = colors.color2, fg = colors.background, bold = true },
			MiniStatuslineModeOther = { bg = colors.color3, fg = colors.background, bold = true },
			MiniStatuslineModeDevInfo = { link = "StatusLine" },
			MiniStatuslineModeFilename = { link = "StatusLineNC" },
			MiniStatuslineModeFileInfo = { link = "StatusLineNC" },
			MiniStatuslineModeInactive = { link = "StatusLineNC" },
		}),
		--: }}}
		--: mini.tabline {{{
		apply_plugin("mini.tabline", {
			MiniTablineCurrent = { link = "TabLineSel" },
			MiniTablineFill = { link = "TabLineFill" },
			MiniTablineVisible = { link = "TabLine" },
			MiniTablineHidden = { link = "MiniTablineVisible" },
			MiniTablineModifiedCurrent = {
				bg = U.lighten(colors.background, 10),
				fg = colors.color3,
				bold = true,
				italic = true,
			},
			MiniTablineModifiedVisible = { fg = colors.color6 },
			MiniTablineModifiedHidden = { fg = colors.color5 },
			MiniTablineTabpagesection = {
				bg = O.transparent and colors.none or U.lighten(colors.background, 10),
				fg = colors.color4,
				bold = true,
				italic = true,
			},
		}),
		--: }}}
		--: mini.cursorword {{{
		apply_plugin("mini.cursorword", {
			MiniCursorword = { underline = true },
			MiniCursorwordCurrent = { link = "MiniCursorword" },
		}),
		--: }}}
		--: mini.files {{{
		apply_plugin("mini.files", {
			MiniFilesBorder = { link = "FloatBorder" },
			MiniFilesBorderModified = { link = "DiagnosticWarn" },
			MiniFilesCursorLine = { link = "CursorLine" },
			MiniFilesDirectory = { link = "Directory" },
			MiniFilesFile = {},
			MiniFilesNormal = { link = "NormalFloat" },
			MiniFilesTitle = { link = "Comment" },
			MiniFilesTitleFocused = { link = "FloatTitle" },
		}),
		--: }}}
		--: mini.hipatterns {{{
		apply_plugin("mini.hipatterns", {
			MiniHipatternsFixme = { bg = colors.color1, fg = colors.background, bold = true, italic = true },
			MiniHipatternsHack = { bg = colors.color11, fg = colors.background, bold = true, italic = true },
			MiniHipatternsTodo = { link = "Todo" },
			MiniHipatternsNote = { link = "Note" },
		}),
		--: }}}
		--: mini.pick {{{
		apply_plugin("mini.pick", {
			MiniPickBorder = { link = "FloatBorder" },
			MiniPickBorderBusy = { link = "DiagnosticWarn" },
			MiniPickBorderText = { link = "FloatTitle" },
			MiniPickIconDirectory = { link = "Directory" },
			MiniPickNormal = { link = "NormalFloat" },
			MiniPickIconFile = { link = "MiniPickNormal" },
			MiniPickHeader = { link = "DiagnosticHint" },
			MiniPickMatchCurrent = { link = "CursorLine" },
			MiniPickMatchMarked = { link = "Visual" },
			MiniPickMatchRanges = { fg = colors.color4 },
			MiniPickPreviewLine = { link = "CursorLine" },
			MiniPickPreviewRegion = { link = "IncSearch" },
			MiniPickPrompt = { link = "FloatTitle" },
		}),
		--: }}}
		--: mini.starter: {{{
		apply_plugin("mini.starter", {
			MiniStarterCurrent = { link = "CursorLine" },
			MiniStarterHeader = { fg = colors.color4, bold = true, italic = true },
			MiniStarterFooter = { fg = colors.color5, bold = true, italic = true },
			MiniStarterInactive = { link = "Comment" },
			MiniStarterItem = { link = "Normal" },
			MiniStarterItemBullet = { link = "Delimiter" },
			MiniStarterItemPrefix = { fg = colors.foreground, bold = true, italic = true },
			MiniStarterSection = { fg = colors.color6, bold = true, italic = true },
			MiniStarterQuery = { fg = colors.color1 },
		}),
		--: }}}
		--: }}}
		{}
	)
end

return M
