local M = {}

M.get = function(colors)
	return {
		-- neoclide/coc.nvim
		CocHighlightText             = { bold = true },
		CocHoverRange                = { bold = true, underline = true },
		CocHintHighlight             = { fg = colors.color2, undercurl = true },
		CocErrorFloat                = { bg = colors.color8, fg = colors.color1 },
		CocWarningFloat              = { bg = colors.color8, fg = colors.color3 },
		CocInfoFloat                 = { bg = colors.color8, fg = colors.color4 },
		CocHintFloat                 = { bg = colors.color8, fg = colors.color2 },
		CocCodeLens                  = { fg = colors.color8 },
		CocErrorSign                 = { link = "ALEErrorSign" },
		CocWarningSign               = { link = "ALEWarningSign" },
		CocInfoSign                  = { link = "ALEInfoSign" },
		CocHintSign                  = { link = "Label" },
		CocErrorHighlight            = { link = "ALEError" },
		CocWarningHighlight          = { link = "ALEWarning" },
		CocInfoHighlight             = { link = "ALEInfo" },
		CocWarningVirtualText        = { link = "ALEVirtualTextWarning" },
		CocErrorVirtualText          = { link = "ALEVirtualTextError" },
		CocInfoVirtualText           = { link = "ALEVirtualTextInfo" },
		CocHintVirtualText           = { link = "ALEVirtualTextInfo" },
		CocGitAddedSign              = { link = "GitGutterAdd" },
		CocGitChangeRemovedSign      = { link = "GitGutterChangeDelete" },
		CocGitChangedSign            = { link = "GitGutterChange" },
		CocGitRemovedSign            = { link = "GitGutterDelete" },
		CocGitTopRemovedSign         = { link = "GitGutterDelete" },
		CocExplorerBufferRoot        = { fg = colors.color1 },
		CocExplorerBufferExpandIcon  = { fg = colors.color4 },
		CocExplorerBufferBufnr       = { fg = colors.color3 },
		CocExplorerBufferModified    = { fg = colors.color1 },
		CocExplorerBufferBufname     = { fg = colors.color8 },
		CocExplorerBufferFullpath    = { fg = colors.color8 },
		CocExplorerFileRoot          = { fg = colors.color1 },
		CocExplorerFileExpandIcon    = { fg = colors.color4 },
		CocExplorerFileFullpath      = { fg = colors.color8 },
		CocExplorerFileDirectory     = { fg = colors.color2 },
		CocExplorerFileGitStage      = { fg = colors.color4 },
		CocExplorerFileGitUnstage    = { fg = colors.color3 },
		CocExplorerFileSize          = { fg = colors.color4 },
		CocExplorerTimeAccessed      = { fg = colors.color5 },
		CocExplorerTimeCreated       = { fg = colors.color5 },
		CocExplorerTimeModified      = { fg = colors.color5 },
		CocExplorerFileRootName      = { fg = colors.color11 },
	}
end

return M
