local M = {}

M.get = function(colors)
	return {
		-- nvim-telescope/telescope.nvim
		TelescopeNormal                 = { link = "Normal" },
		TelescopeBorder                 = { link = "FloatBorder" },
		TelescopeSelection              = { link = "CursorLine" },
		TelescopeMatching               = { fg = colors.color4, bold = true },
		TelescopePromptBorder           = { link = "TelescopeBorder" },
		TelescopePromptNormal           = { fg = colors.foreground },
		TelescopePromptPrefix           = { fg = colors.color4, bold = true },
		TelescopePreviewTitle           = { fg = colors.color3 },
		TelescopePromptTitle            = { fg = colors.color4 },
		TelescopeResultsTitle           = { fg = colors.color6 },
		TelescopeSelectionCaret         = { fg = colors.color6 },
		TelescopeResultsVariable        = { link = "SpecialChar" },
		TelescopeResultsStruct          = { link = "Struct" },
		TelescopeResultsOperator        = { link = "Operator" },
		TelescopeResultsMethod          = { link = "Method" },
		TelescopeResultsFunction        = { link = "Function" },
		TelescopeResultsField           = { link = "Function" },
		TelescopeResultsConstant        = { link = "Constant" },
		TelescopeResultsClass           = { link = "Function" },
		TelescopePreviewMessageFillchar = { link = "TelescopePreviewMessage" },
		TelescopePreviewMessage         = { link = "TelescopePreviewNormal" },
		TelescopePreviewNormal          = { link = "TelescopeNormal" },
		TelescopePreviewDate            = { link = "Directory" },
		TelescopePreviewGroup           = { link = "Constant" },
		TelescopePreviewUser            = { link = "Constant" },
		TelescopePreviewSize            = { link = "String" },
		TelescopePreviewSticky          = { link = "Keyword" },
		TelescopePreviewHyphen          = { link = "NonText" },
		TelescopePreviewExecute         = { link = "String" },
		TelescopePreviewWrite           = { link = "Statement" },
		TelescopePreviewRead            = { link = "Constant" },
		TelescopePreviewSocket          = { link = "Statement" },
		TelescopePreviewLink            = { link = "Special" },
		TelescopePreviewBlock           = { link = "Constant" },
		TelescopePreviewDirectory       = { link = "Directory" },
		TelescopePreviewCharDev         = { link = "Constant" },
		TelescopePreviewPipe            = { link = "Constant" },
		TelescopePreviewMatch           = { link = "Search" },
		TelescopePreviewLine            = { link = "Visual" },
		TelescopePromptCounter          = { link = "NonText" },
		TelescopeTitle                  = { link = "TelescopeBorder" },
		TelescopePreviewBorder          = { link = "TelescopeBorder" },
		TelescopeResultsBorder          = { link = "TelescopeBorder" },
		TelescopeResultsNormal          = { link = "TelescopeNormal" },
		TelescopeMultiIcon              = { link = "Identifier" },
		TelescopeMultiSelection         = { link = "Type" },
		TelescopeResultsDiffUntracked   = { link = "NonText" },
		TelescopeResultsDiffDelete      = { link = "DiffDelete" },
		TelescopeResultsDiffAdd         = { link = "DiffAdd" },
		TelescopeResultsDiffChange      = { link = "DiffChange" },
		TelescopeResultsSpecialComment  = { link = "SpecialComment" },
		TelescopeResultsComment         = { link = "Comment" },
		TelescopeResultsNumber          = { link = "Number" },
		TelescopeResultsIdentifier      = { link = "Identifier" },
	}
end

return M
